/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Pelicula;
import Clases.Serie;
import Clases.Temporada;
import java.awt.Color;
import Clases.UtilJavaflix;
import Excepciones.FaltanDatos;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco
 */
public class addContenido extends javax.swing.JFrame {

    private adminContenidos padre;
    private ArrayList<Temporada> temporadas = new ArrayList<Temporada>();
    private String nombreImagen, rutaImagen, extension = "jpg";
    private File file;
    private BufferedImage bimage;
    private ImageIcon portadaparasubir = null;

    public ArrayList<Temporada> getTemporadas() {
        return temporadas;
    }

    public void setTemporadas(ArrayList<Temporada> temporadas) {
        this.temporadas = temporadas;
    }

    public void addTemporadas(Temporada temporada) {
        this.temporadas.add(temporada);
    }

    private void showTabla(ArrayList<Temporada> Temporadas) {
        int contador = 0;
        DefaultTableModel model = (DefaultTableModel) jTableTemporadas.getModel();
        for (Temporada temporadaactual : Temporadas) {
            model.addRow(new Object[]{null, null});
            jTableTemporadas.setValueAt(Temporadas.indexOf(temporadaactual) + 1, contador, 0);
            jTableTemporadas.setValueAt(temporadaactual.getCapitulos().size(), contador, 1);
            contador++;
        }
        jTableTemporadas.setModel(model);
    }

    private void limpiarTabla() {
        DefaultTableModel dm = (DefaultTableModel) jTableTemporadas.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }

    public ImageIcon cargarFoto() {
        JFileChooser filechooser = new JFileChooser();
        filechooser.addChoosableFileFilter(new ImageFilter());
        filechooser.setAcceptAllFileFilterUsed(false);

        int option = filechooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            file = filechooser.getSelectedFile();
            rutaImagen = file.getAbsolutePath();
            nombreImagen = file.getName();
        } else {
            JOptionPane.showMessageDialog(this, "Ningún fichero seleccionado", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        ImageIcon portada = new ImageIcon(rutaImagen);
        return portada;
    }

    /**
     * Creates new form ventanaPrincipal
     */
    public addContenido(adminContenidos main) {
        padre = main;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        jPanelPeliculas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelventana = new javax.swing.JPanel();
        jPanelOpciones = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanelAtras = new javax.swing.JPanel();
        jLabelAtras = new javax.swing.JLabel();
        jPaneladd = new javax.swing.JPanel();
        jPanelSeries = new javax.swing.JPanel();
        jLabelNombreS = new javax.swing.JLabel();
        fieldNombreS = new javax.swing.JTextField();
        jLabelSinopsisS = new javax.swing.JLabel();
        jLabelGeneroS = new javax.swing.JLabel();
        fieldGeneroS = new javax.swing.JTextField();
        jLabelAnnoS = new javax.swing.JLabel();
        fieldAnnoS = new javax.swing.JTextField();
        jLabelActoresS = new javax.swing.JLabel();
        fieldActoresS = new javax.swing.JTextField();
        jScrollPaneTemporadas = new javax.swing.JScrollPane();
        jTableTemporadas = new javax.swing.JTable();
        jButtonAnnadirS = new javax.swing.JButton();
        jScrollPaneSinopsisS = new javax.swing.JScrollPane();
        fieldSinopsisS = new javax.swing.JTextArea();
        jPanelCrearSerie = new javax.swing.JPanel();
        crearserie = new javax.swing.JLabel();
        jPanelFotoS = new javax.swing.JPanel();
        jLabelportadaserie = new javax.swing.JLabel();
        jButtonSubirFoto = new javax.swing.JButton();
        jPanelPeliculas = new javax.swing.JPanel();
        fieldTituloP = new javax.swing.JTextField();
        jLabelTituloP = new javax.swing.JLabel();
        jLabelGeneroP = new javax.swing.JLabel();
        fieldGeneroP = new javax.swing.JTextField();
        jLabelSinopsisP = new javax.swing.JLabel();
        jScrollPaneSinopsisP = new javax.swing.JScrollPane();
        fieldSinopsisP = new javax.swing.JTextArea();
        fieldAnnoP = new javax.swing.JTextField();
        jLabelAnno = new javax.swing.JLabel();
        jLabelDirector = new javax.swing.JLabel();
        fieldDirector = new javax.swing.JTextField();
        jLabelDuracionP = new javax.swing.JLabel();
        fieldDuracion = new javax.swing.JFormattedTextField();
        jButtonFotoP = new javax.swing.JButton();
        jPanelFotoP = new javax.swing.JPanel();
        jLabelportadapelicula = new javax.swing.JLabel();
        jPanelCrearPelicula = new javax.swing.JPanel();
        crearpelicula = new javax.swing.JLabel();
        jLabelActores = new javax.swing.JLabel();
        fieldActoresP = new javax.swing.JTextField();
        paneladdserie = new javax.swing.JPanel();
        addserielabel = new javax.swing.JLabel();
        paneladdpelicula = new javax.swing.JPanel();
        addpeliculalabel = new javax.swing.JLabel();
        jLabelJAVAFLIX = new javax.swing.JLabel();
        jLabelJAVAFLIXSombra = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1239, 725));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });
        jPanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCerrar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("X");
        jPanelCerrar.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanelOpciones.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanelAtras.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseExited(evt);
            }
        });
        jPanelAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAtras.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAtras.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabelAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAtras.setText("< ");
        jPanelAtras.add(jLabelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        jPanelOpciones.add(jPanelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 30));

        jPanelventana.add(jPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, -1));

        jPaneladd.setBackground(new java.awt.Color(255, 255, 255));

        jPanelSeries.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeries.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreS.setText("Nombre:");
        jPanelSeries.add(jLabelNombreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 20));
        jPanelSeries.add(fieldNombreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 105, -1));

        jLabelSinopsisS.setText("Sinopsis:");
        jPanelSeries.add(jLabelSinopsisS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, 20));

        jLabelGeneroS.setText("Genero:");
        jPanelSeries.add(jLabelGeneroS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 20));
        jPanelSeries.add(fieldGeneroS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 105, -1));

        jLabelAnnoS.setText("Año:");
        jPanelSeries.add(jLabelAnnoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));
        jPanelSeries.add(fieldAnnoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 105, -1));

        jLabelActoresS.setText("Actores(separados por ,):");
        jPanelSeries.add(jLabelActoresS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));
        jPanelSeries.add(fieldActoresS, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 320, -1));

        jTableTemporadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Temporada", "Capitulos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneTemporadas.setViewportView(jTableTemporadas);

        jPanelSeries.add(jScrollPaneTemporadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 178, 220, 144));

        jButtonAnnadirS.setText("Añadir Temporada");
        jButtonAnnadirS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirSActionPerformed(evt);
            }
        });
        jPanelSeries.add(jButtonAnnadirS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 133, -1));

        fieldSinopsisS.setColumns(20);
        fieldSinopsisS.setLineWrap(true);
        fieldSinopsisS.setRows(5);
        fieldSinopsisS.setWrapStyleWord(true);
        jScrollPaneSinopsisS.setViewportView(fieldSinopsisS);

        jPanelSeries.add(jScrollPaneSinopsisS, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 210, 90));

        jPanelCrearSerie.setBackground(new java.awt.Color(180, 45, 49));

        crearserie.setBackground(new java.awt.Color(255, 255, 255));
        crearserie.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        crearserie.setForeground(new java.awt.Color(255, 255, 255));
        crearserie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearserie.setText("CREAR SERIE");
        crearserie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearserieMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearSerieLayout = new javax.swing.GroupLayout(jPanelCrearSerie);
        jPanelCrearSerie.setLayout(jPanelCrearSerieLayout);
        jPanelCrearSerieLayout.setHorizontalGroup(
            jPanelCrearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearserie, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        jPanelCrearSerieLayout.setVerticalGroup(
            jPanelCrearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearserie, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanelSeries.add(jPanelCrearSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 720, 80));

        jPanelFotoS.setBackground(new java.awt.Color(130, 130, 130));

        javax.swing.GroupLayout jPanelFotoSLayout = new javax.swing.GroupLayout(jPanelFotoS);
        jPanelFotoS.setLayout(jPanelFotoSLayout);
        jPanelFotoSLayout.setHorizontalGroup(
            jPanelFotoSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelportadaserie, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );
        jPanelFotoSLayout.setVerticalGroup(
            jPanelFotoSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelportadaserie, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );

        jPanelSeries.add(jPanelFotoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jButtonSubirFoto.setText("Subir Foto");
        jButtonSubirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubirFotoActionPerformed(evt);
            }
        });
        jPanelSeries.add(jButtonSubirFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 89, -1));

        jPanelPeliculas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPeliculas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelPeliculas.add(fieldTituloP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 105, -1));

        jLabelTituloP.setText("Título:");
        jPanelPeliculas.add(jLabelTituloP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        jLabelGeneroP.setText("Genero:");
        jPanelPeliculas.add(jLabelGeneroP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));
        jPanelPeliculas.add(fieldGeneroP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 105, -1));

        jLabelSinopsisP.setText("Sinopsis:");
        jPanelPeliculas.add(jLabelSinopsisP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        fieldSinopsisP.setColumns(20);
        fieldSinopsisP.setLineWrap(true);
        fieldSinopsisP.setRows(5);
        fieldSinopsisP.setWrapStyleWord(true);
        jScrollPaneSinopsisP.setViewportView(fieldSinopsisP);

        jPanelPeliculas.add(jScrollPaneSinopsisP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 90));
        jPanelPeliculas.add(fieldAnnoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 105, -1));

        jLabelAnno.setText("Año:");
        jPanelPeliculas.add(jLabelAnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        jLabelDirector.setText("Director:");
        jPanelPeliculas.add(jLabelDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 58, 20));
        jPanelPeliculas.add(fieldDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 110, -1));

        jLabelDuracionP.setText("Duracion(HH:MM:SS)");
        jPanelPeliculas.add(jLabelDuracionP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));
        jPanelPeliculas.add(fieldDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 110, -1));

        jButtonFotoP.setText("Subir Foto");
        jButtonFotoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoPActionPerformed(evt);
            }
        });
        jPanelPeliculas.add(jButtonFotoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 89, -1));

        jPanelFotoP.setBackground(new java.awt.Color(130, 130, 130));

        javax.swing.GroupLayout jPanelFotoPLayout = new javax.swing.GroupLayout(jPanelFotoP);
        jPanelFotoP.setLayout(jPanelFotoPLayout);
        jPanelFotoPLayout.setHorizontalGroup(
            jPanelFotoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelportadapelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );
        jPanelFotoPLayout.setVerticalGroup(
            jPanelFotoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelportadapelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );

        jPanelPeliculas.add(jPanelFotoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jPanelCrearPelicula.setBackground(new java.awt.Color(180, 45, 49));

        crearpelicula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        crearpelicula.setForeground(new java.awt.Color(255, 255, 255));
        crearpelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearpelicula.setText("CREAR PELICULA");
        crearpelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearpeliculaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearPeliculaLayout = new javax.swing.GroupLayout(jPanelCrearPelicula);
        jPanelCrearPelicula.setLayout(jPanelCrearPeliculaLayout);
        jPanelCrearPeliculaLayout.setHorizontalGroup(
            jPanelCrearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearpelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        jPanelCrearPeliculaLayout.setVerticalGroup(
            jPanelCrearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearpelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanelPeliculas.add(jPanelCrearPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 670, -1));

        jLabelActores.setText("Actores(separados por ,):");
        jPanelPeliculas.add(jLabelActores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));
        jPanelPeliculas.add(fieldActoresP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 150, -1));

        javax.swing.GroupLayout jPaneladdLayout = new javax.swing.GroupLayout(jPaneladd);
        jPaneladd.setLayout(jPaneladdLayout);
        jPaneladdLayout.setHorizontalGroup(
            jPaneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneladdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPaneladdLayout.setVerticalGroup(
            jPaneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneladdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSeries, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jPanelPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelventana.add(jPaneladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 900, 480));

        paneladdserie.setBackground(new java.awt.Color(148, 13, 30));

        addserielabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        addserielabel.setForeground(new java.awt.Color(255, 255, 255));
        addserielabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addserielabel.setText("Añadir Serie");
        addserielabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addserielabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addserielabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addserielabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneladdserieLayout = new javax.swing.GroupLayout(paneladdserie);
        paneladdserie.setLayout(paneladdserieLayout);
        paneladdserieLayout.setHorizontalGroup(
            paneladdserieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addserielabel, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        paneladdserieLayout.setVerticalGroup(
            paneladdserieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addserielabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanelventana.add(paneladdserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 170, -1));

        paneladdpelicula.setBackground(new java.awt.Color(255, 255, 255));

        addpeliculalabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        addpeliculalabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addpeliculalabel.setText("Añadir Pelicula");
        addpeliculalabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addpeliculalabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addpeliculalabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addpeliculalabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneladdpeliculaLayout = new javax.swing.GroupLayout(paneladdpelicula);
        paneladdpelicula.setLayout(paneladdpeliculaLayout);
        paneladdpeliculaLayout.setHorizontalGroup(
            paneladdpeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addpeliculalabel, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        paneladdpeliculaLayout.setVerticalGroup(
            paneladdpeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addpeliculalabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanelventana.add(paneladdpelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, -1, -1));

        jLabelJAVAFLIX.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJAVAFLIX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIX.setText("JAVAFLIX");
        jPanelventana.add(jLabelJAVAFLIX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, 130));

        jLabelJAVAFLIXSombra.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIXSombra.setForeground(new java.awt.Color(112, 101, 101));
        jLabelJAVAFLIXSombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIXSombra.setText("JAVAFLIX");
        jPanelventana.add(jLabelJAVAFLIXSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 810, 130));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/palomitasbienrojo.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel2");
        jPanelventana.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1239, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelventana, javax.swing.GroupLayout.PREFERRED_SIZE, 1239, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelventana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        UtilJavaflix.guardarDatos();
        padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        // TODO add your handling code here:
        jPanelCerrar.setBackground(new Color(232, 17, 35));
        jLabelCerrar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        // TODO add your handling code here:
        jPanelCerrar.setBackground(new Color(255, 255, 255));
        jLabelCerrar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void jPanelAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseEntered
        // TODO add your handling code here:
        jPanelAtras.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_jPanelAtrasMouseEntered

    private void jPanelAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseExited
        // TODO add your handling code here:
        jPanelAtras.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jPanelAtrasMouseExited

    private void jPanelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_jPanelAtrasMouseClicked

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        // TODO add your handling code here:      
        UtilJavaflix.cerrarPrograma();

    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (this.temporadas.size() > 0) {
            limpiarTabla();
            showTabla(temporadas);
        }
    }//GEN-LAST:event_formWindowActivated

    private void addserielabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addserielabelMouseEntered
        // TODO add your handling code here:
        if (!paneladdserie.getBackground().equals(new Color(148, 13, 30))) {
            paneladdserie.setBackground(new Color(180, 45, 49));
            addserielabel.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_addserielabelMouseEntered

    private void addserielabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addserielabelMouseExited
        // TODO add your handling code here:
        if (!paneladdserie.getBackground().equals(new Color(148, 13, 30))) {
            paneladdserie.setBackground(new Color(255, 255, 255));
            addserielabel.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_addserielabelMouseExited

    private void addpeliculalabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpeliculalabelMouseEntered
        // TODO add your handling code here:
        if (!paneladdpelicula.getBackground().equals(new Color(148, 13, 30))) {
            paneladdpelicula.setBackground(new Color(180, 45, 49));
            addpeliculalabel.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_addpeliculalabelMouseEntered

    private void addpeliculalabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpeliculalabelMouseExited
        // TODO add your handling code here:
        if (!paneladdpelicula.getBackground().equals(new Color(148, 13, 30))) {
            paneladdpelicula.setBackground(new Color(255, 255, 255));
            addpeliculalabel.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_addpeliculalabelMouseExited

    private void addserielabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addserielabelMouseClicked
        // TODO add your handling code here:
        paneladdserie.setBackground(new Color(148, 13, 30));
        paneladdpelicula.setBackground(new Color(255, 255, 255));
        addpeliculalabel.setForeground(new Color(0, 0, 0));
        jPanelSeries.setVisible(true);
        jPanelPeliculas.setVisible(false);
    }//GEN-LAST:event_addserielabelMouseClicked

    private void addpeliculalabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpeliculalabelMouseClicked
        // TODO add your handling code here:
        paneladdserie.setBackground(new Color(255, 255, 255));
        paneladdpelicula.setBackground(new Color(148, 13, 30));
        addserielabel.setForeground(new Color(0, 0, 0));
        jPanelSeries.setVisible(false);
        jPanelPeliculas.setVisible(true);
    }//GEN-LAST:event_addpeliculalabelMouseClicked

    private void jButtonFotoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoPActionPerformed
        // TODO add your handling code here:        
        this.portadaparasubir = cargarFoto();
        ImageIcon imgRedimensionada = new ImageIcon(portadaparasubir.getImage().getScaledInstance(jLabelportadapelicula.getWidth(), jLabelportadapelicula.getHeight(), 1));
        jLabelportadapelicula.setIcon(imgRedimensionada);
    }//GEN-LAST:event_jButtonFotoPActionPerformed

    private void jButtonSubirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubirFotoActionPerformed
        // TODO add your handling code here:
        this.portadaparasubir = cargarFoto();
        ImageIcon imgRedimensionada = new ImageIcon(portadaparasubir.getImage().getScaledInstance(jLabelportadaserie.getWidth(), jLabelportadaserie.getHeight(), 1));
        jLabelportadaserie.setIcon(imgRedimensionada);
    }//GEN-LAST:event_jButtonSubirFotoActionPerformed

    private void jButtonAnnadirSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirSActionPerformed
        // TODO add your handling code here:
        addCapitulo nuevatemporada = new addCapitulo(this);
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonAnnadirSActionPerformed

    private void crearpeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearpeliculaMouseClicked
        // TODO add your handling code here:
        try {
            if (portadaparasubir == null) {
                throw new FaltanDatos("No se ha subido una portada");
            }
            Pelicula nuevapelicula = new Pelicula(fieldDuracion.getText(), fieldDirector.getText(), fieldTituloP.getText(),
                    fieldSinopsisP.getText(), fieldGeneroP.getText(), Integer.parseInt(fieldAnnoP.getText()),
                    UtilJavaflix.parseActores(fieldActoresP.getText()), portadaparasubir);
            UtilJavaflix.addPelicula(nuevapelicula);
            UtilJavaflix.guardarDatos();
            JOptionPane.showMessageDialog(this, "Pelicula creada correctamente");
        } catch (FaltanDatos ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al crear pelicula\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_crearpeliculaMouseClicked

    private void crearserieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearserieMouseClicked
        // TODO add your handling code here:
        try {
            if (portadaparasubir == null) {
                throw new FaltanDatos("No se ha subido una portada");
            }
            Serie nuevaserie = new Serie(temporadas, fieldNombreS.getText(), fieldSinopsisS.getText(), fieldGeneroS.getText(), Integer.parseInt(fieldAnnoS.getText()),
                    UtilJavaflix.parseActores(fieldActoresS.getText()), portadaparasubir);
            UtilJavaflix.addSerie(nuevaserie);
            UtilJavaflix.guardarDatos();
            JOptionPane.showMessageDialog(this, "Serie creada correctamente");
        } catch (FaltanDatos ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al crear serie\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_crearserieMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addpeliculalabel;
    private javax.swing.JLabel addserielabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel crearpelicula;
    private javax.swing.JLabel crearserie;
    private javax.swing.JTextField fieldActoresP;
    private javax.swing.JTextField fieldActoresS;
    private javax.swing.JTextField fieldAnnoP;
    private javax.swing.JTextField fieldAnnoS;
    private javax.swing.JTextField fieldDirector;
    private javax.swing.JFormattedTextField fieldDuracion;
    private javax.swing.JTextField fieldGeneroP;
    private javax.swing.JTextField fieldGeneroS;
    private javax.swing.JTextField fieldNombreS;
    private javax.swing.JTextArea fieldSinopsisP;
    private javax.swing.JTextArea fieldSinopsisS;
    private javax.swing.JTextField fieldTituloP;
    private javax.swing.JButton jButtonAnnadirS;
    private javax.swing.JButton jButtonFotoP;
    private javax.swing.JButton jButtonSubirFoto;
    private javax.swing.JLabel jLabelActores;
    private javax.swing.JLabel jLabelActoresS;
    private javax.swing.JLabel jLabelAnno;
    private javax.swing.JLabel jLabelAnnoS;
    private javax.swing.JLabel jLabelAtras;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelDuracionP;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGeneroP;
    private javax.swing.JLabel jLabelGeneroS;
    private javax.swing.JLabel jLabelJAVAFLIX;
    private javax.swing.JLabel jLabelJAVAFLIXSombra;
    private javax.swing.JLabel jLabelNombreS;
    private javax.swing.JLabel jLabelSinopsisP;
    private javax.swing.JLabel jLabelSinopsisS;
    private javax.swing.JLabel jLabelTituloP;
    private javax.swing.JLabel jLabelportadapelicula;
    private javax.swing.JLabel jLabelportadaserie;
    private javax.swing.JPanel jPanelAtras;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelCrearPelicula;
    private javax.swing.JPanel jPanelCrearSerie;
    private javax.swing.JPanel jPanelFotoP;
    private javax.swing.JPanel jPanelFotoS;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPeliculas;
    private javax.swing.JPanel jPanelSeries;
    private javax.swing.JPanel jPaneladd;
    private javax.swing.JPanel jPanelventana;
    private javax.swing.JScrollPane jScrollPaneSinopsisP;
    private javax.swing.JScrollPane jScrollPaneSinopsisS;
    private javax.swing.JScrollPane jScrollPaneTemporadas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableTemporadas;
    private javax.swing.JPanel paneladdpelicula;
    private javax.swing.JPanel paneladdserie;
    // End of variables declaration//GEN-END:variables
}
