/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Contenido;
import Clases.Pelicula;
import Clases.Serie;
import java.awt.Color;
import Clases.UtilJavaflix;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco
 */
public class consultaContenido extends javax.swing.JFrame {

    private adminContenidos padre;
    private ArrayList<Contenido> tablaactual = new ArrayList<Contenido>();

    public ArrayList<Contenido> getTablaactual() {
        return tablaactual;
    }

    public void setTablaactual(ArrayList<Contenido> tablaactual) {
        this.tablaactual = tablaactual;
    }

    /**
     * Creates new form ventanaPrincipal
     */
    public consultaContenido(adminContenidos main) {
        padre = main;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        tablaactual.addAll(UtilJavaflix.getPeliculas());
        tablaactual.addAll(UtilJavaflix.getSeries());
        showTabla(tablaactual);
        System.out.println(tablaactual);

    }

    private void showTabla(ArrayList<Contenido> contenido_a_ordenar) {
        int contador = 0;
        DefaultTableModel model = (DefaultTableModel) jTableContenidos.getModel();
        for (Contenido contenido : contenido_a_ordenar) {
            model.addRow(new Object[]{null, null});
            jTableContenidos.setValueAt(contenido.getTitulo(), contador, 0);
            jTableContenidos.setValueAt(contenido.getClass().getName(), contador, 1);
            contador++;
        }
    }

    private void limpiarTabla() {
        DefaultTableModel dm = (DefaultTableModel) jTableContenidos.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }

    private void recargarDatosTabla() {
        tablaactual.clear();
        tablaactual.addAll(UtilJavaflix.getPeliculas());
        tablaactual.addAll(UtilJavaflix.getSeries());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelventana = new javax.swing.JPanel();
        jPanelOpciones = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanelAtras = new javax.swing.JPanel();
        jLabelAtras = new javax.swing.JLabel();
        jPanelContenidos = new javax.swing.JPanel();
        jScrollPaneContenidos = new javax.swing.JScrollPane();
        jTableContenidos = new javax.swing.JTable();
        jLabelAjustes = new javax.swing.JLabel();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jPanelBuscar = new javax.swing.JPanel();
        labelsearch = new javax.swing.JLabel();
        jLabelAclaracion = new javax.swing.JLabel();
        jLabelJAVAFLIX = new javax.swing.JLabel();
        jLabelJAVAFLIXSombra = new javax.swing.JLabel();
        jLabelFondoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1239, 725));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });
        jPanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCerrar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("X");
        jPanelCerrar.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanelOpciones.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanelAtras.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseExited(evt);
            }
        });
        jPanelAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAtras.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAtras.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabelAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAtras.setText("< ");
        jPanelAtras.add(jLabelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        jPanelOpciones.add(jPanelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 30));

        jPanelventana.add(jPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, -1));

        jPanelContenidos.setBackground(new java.awt.Color(255, 255, 255));

        jTableContenidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableContenidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableContenidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableContenidosMouseClicked(evt);
            }
        });
        jScrollPaneContenidos.setViewportView(jTableContenidos);

        jLabelAjustes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelAjustes.setText("Ajustes de consulta");

        jLabelBuscar.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabelBuscar.setText("Buscar:");

        jTextFieldBuscar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        jPanelBuscar.setBackground(new java.awt.Color(180, 45, 49));

        labelsearch.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        labelsearch.setForeground(new java.awt.Color(255, 255, 255));
        labelsearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsearch.setText("Buscar");
        labelsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelsearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        jLabelAclaracion.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabelAclaracion.setText("Haga clic en un contenido para modificarlo");

        javax.swing.GroupLayout jPanelContenidosLayout = new javax.swing.GroupLayout(jPanelContenidos);
        jPanelContenidos.setLayout(jPanelContenidosLayout);
        jPanelContenidosLayout.setHorizontalGroup(
            jPanelContenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelContenidosLayout.createSequentialGroup()
                .addGroup(jPanelContenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenidosLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanelContenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBuscar)
                            .addGroup(jPanelContenidosLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAjustes)
                        .addGap(42, 42, 42)))
                .addGroup(jPanelContenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAclaracion)
                    .addComponent(jScrollPaneContenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelContenidosLayout.setVerticalGroup(
            jPanelContenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenidosLayout.createSequentialGroup()
                .addGroup(jPanelContenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenidosLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabelAjustes)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBuscar)
                            .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContenidosLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPaneContenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelAclaracion)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanelventana.add(jPanelContenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabelJAVAFLIX.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJAVAFLIX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIX.setText("JAVAFLIX");
        jPanelventana.add(jLabelJAVAFLIX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, 130));

        jLabelJAVAFLIXSombra.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIXSombra.setForeground(new java.awt.Color(112, 101, 101));
        jLabelJAVAFLIXSombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIXSombra.setText("JAVAFLIX");
        jPanelventana.add(jLabelJAVAFLIXSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 810, 130));

        jLabelFondoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/palomitasbienrojo.jpg"))); // NOI18N
        jLabelFondoRegistro.setText("jLabel2");
        jPanelventana.add(jLabelFondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1239, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelventana, javax.swing.GroupLayout.PREFERRED_SIZE, 1239, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelventana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        UtilJavaflix.guardarDatos();
        padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        // TODO add your handling code here:
        jPanelCerrar.setBackground(new Color(232, 17, 35));
        jLabelCerrar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        // TODO add your handling code here:
        jPanelCerrar.setBackground(new Color(255, 255, 255));
        jLabelCerrar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void jPanelAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseEntered
        // TODO add your handling code here:
        jPanelAtras.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_jPanelAtrasMouseEntered

    private void jPanelAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseExited
        // TODO add your handling code here:
        jPanelAtras.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jPanelAtrasMouseExited

    private void jPanelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_jPanelAtrasMouseClicked

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        // TODO add your handling code here:      
        UtilJavaflix.cerrarPrograma();
    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void jTableContenidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableContenidosMouseClicked
        // Codigo para pedir al admin si quiere elimnar al usuario clicado dentro de la tabla
        try {
            ArrayList<Contenido> tablaactual_temporal = getTablaactual();
            Contenido contenidoselect = tablaactual_temporal.get(jTableContenidos.getSelectedRow());
            if (contenidoselect instanceof Serie) {
                modificarSeries seriemod = new modificarSeries(this,(Serie) contenidoselect);
                this.setEnabled(false);
            } else if (contenidoselect instanceof Pelicula) {
                modificarPelicula pelimod = new modificarPelicula(this, (Pelicula) contenidoselect);
                this.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error al intentar modificar el elemento", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IndexOutOfBoundsException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jTableContenidosMouseClicked

    private void labelsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsearchMouseClicked
        // TODO add your handling code here:
        try {
            ArrayList<Contenido> clientesfiltrados = new ArrayList<>();
            tablaactual.stream()
                    .filter(filtrando -> (filtrando.getTitulo().contains(jTextFieldBuscar.getText())))
                    .forEachOrdered(filtrando -> {
                        clientesfiltrados.add(filtrando);
                    });
            limpiarTabla();
            setTablaactual(clientesfiltrados);
            showTabla(getTablaactual());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_labelsearchMouseClicked

    private void labelsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsearchMouseEntered
        // TODO add your handling code here:
        jPanelBuscar.setBackground(new Color(148, 13, 30));
    }//GEN-LAST:event_labelsearchMouseEntered

    private void labelsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsearchMouseExited
        // TODO add your handling code here:
        jPanelBuscar.setBackground(new Color(180, 45, 49));
    }//GEN-LAST:event_labelsearchMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        limpiarTabla();
        recargarDatosTabla();
        showTabla(tablaactual);
    }//GEN-LAST:event_formWindowActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelAclaracion;
    private javax.swing.JLabel jLabelAjustes;
    private javax.swing.JLabel jLabelAtras;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelFondoRegistro;
    private javax.swing.JLabel jLabelJAVAFLIX;
    private javax.swing.JLabel jLabelJAVAFLIXSombra;
    private javax.swing.JPanel jPanelAtras;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelContenidos;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelventana;
    private javax.swing.JScrollPane jScrollPaneContenidos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableContenidos;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JLabel labelsearch;
    // End of variables declaration//GEN-END:variables
}
