/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Cliente;
import Clases.PlanSuscripcion;
import Clases.TarjetaCredito;

import java.awt.Color;

import Clases.UtilJavaflix;
import java.time.LocalDate;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class planregistroUsuario extends javax.swing.JFrame {

    private registroUsuario padre;
    private String dni;
    private String nombre;
    private String email;
    private String pass;
    private TarjetaCredito tarjeta;

    /**
     * Creates new form ventanaPrincipal
     */
    public planregistroUsuario(registroUsuario main, String dni, String nombre, String email, String pass, TarjetaCredito tarjeta) {
        padre = main;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        this.dni = dni;
        this.nombre = nombre;
        this.email = email;
        this.pass = pass;
        this.tarjeta = tarjeta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelventana = new javax.swing.JPanel();
        jPanelOpciones = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanelAtras = new javax.swing.JPanel();
        jLabelAtras = new javax.swing.JLabel();
        jLabelCREATUCUENTA = new javax.swing.JLabel();
        jLabelDoblez = new javax.swing.JLabel();
        jLabelFondoEtiquetas = new javax.swing.JLabel();
        jLabelJAVAFLIX = new javax.swing.JLabel();
        jLabelJAVAFLIXSombra = new javax.swing.JLabel();
        jPanelIntroDatos = new javax.swing.JPanel();
        jLabelJavaFlixBasico = new javax.swing.JLabel();
        jPanelJavaFlixBasicoPrecio = new javax.swing.JPanel();
        jLabelJavaFlixBasicoPrecio = new javax.swing.JLabel();
        jLabelJavaFlixEstandar = new javax.swing.JLabel();
        jPanelJavaFlixEstandarPrecio = new javax.swing.JPanel();
        jLabelJavaFlixEstandarPrecio = new javax.swing.JLabel();
        jLabelJavaFlixPremium = new javax.swing.JLabel();
        jPanelJavaFlixPremiumPrecio = new javax.swing.JPanel();
        jLabelJavaFlixPremiumPrecio = new javax.swing.JLabel();
        jLabelFondoPremiun = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1239, 725));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });
        jPanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCerrar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("X");
        jPanelCerrar.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanelOpciones.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanelAtras.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseExited(evt);
            }
        });
        jPanelAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAtras.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAtras.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabelAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAtras.setText("< ");
        jPanelAtras.add(jLabelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        jPanelOpciones.add(jPanelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 30));

        jPanelventana.add(jPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabelCREATUCUENTA.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabelCREATUCUENTA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCREATUCUENTA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCREATUCUENTA.setText("ELIGE TU PLAN");
        jPanelventana.add(jLabelCREATUCUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 440, 120));

        jLabelDoblez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/doblez.jpg"))); // NOI18N
        jPanelventana.add(jLabelDoblez, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 30, -1));

        jLabelFondoEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoetiquetas.jpg"))); // NOI18N
        jLabelFondoEtiquetas.setText("jLabel7");
        jPanelventana.add(jLabelFondoEtiquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 440, 120));

        jLabelJAVAFLIX.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJAVAFLIX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIX.setText("JAVAFLIX");
        jPanelventana.add(jLabelJAVAFLIX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, 130));

        jLabelJAVAFLIXSombra.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIXSombra.setForeground(new java.awt.Color(112, 101, 101));
        jLabelJAVAFLIXSombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIXSombra.setText("JAVAFLIX");
        jPanelventana.add(jLabelJAVAFLIXSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 810, 130));

        jPanelIntroDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelIntroDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelJavaFlixBasico.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabelJavaFlixBasico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJavaFlixBasico.setText("JavaFlix Básico");
        jPanelIntroDatos.add(jLabelJavaFlixBasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 410, -1));

        jPanelJavaFlixBasicoPrecio.setBackground(new java.awt.Color(180, 45, 49));
        jPanelJavaFlixBasicoPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelJavaFlixBasicoPrecio.setPreferredSize(new java.awt.Dimension(170, 62));
        jPanelJavaFlixBasicoPrecio.setRequestFocusEnabled(false);
        jPanelJavaFlixBasicoPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelJavaFlixBasicoPrecioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelJavaFlixBasicoPrecioMouseExited(evt);
            }
        });

        jLabelJavaFlixBasicoPrecio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelJavaFlixBasicoPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJavaFlixBasicoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJavaFlixBasicoPrecio.setText("8,99€ ");
        jLabelJavaFlixBasicoPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelJavaFlixBasicoPrecioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelJavaFlixBasicoPrecioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelJavaFlixBasicoPrecioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelJavaFlixBasicoPrecioLayout = new javax.swing.GroupLayout(jPanelJavaFlixBasicoPrecio);
        jPanelJavaFlixBasicoPrecio.setLayout(jPanelJavaFlixBasicoPrecioLayout);
        jPanelJavaFlixBasicoPrecioLayout.setHorizontalGroup(
            jPanelJavaFlixBasicoPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelJavaFlixBasicoPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanelJavaFlixBasicoPrecioLayout.setVerticalGroup(
            jPanelJavaFlixBasicoPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJavaFlixBasicoPrecioLayout.createSequentialGroup()
                .addComponent(jLabelJavaFlixBasicoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelIntroDatos.add(jPanelJavaFlixBasicoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 130, 60));

        jLabelJavaFlixEstandar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabelJavaFlixEstandar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJavaFlixEstandar.setText("JavaFlix Estándar\n");
        jPanelIntroDatos.add(jLabelJavaFlixEstandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 410, -1));

        jPanelJavaFlixEstandarPrecio.setBackground(new java.awt.Color(180, 45, 49));
        jPanelJavaFlixEstandarPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelJavaFlixEstandarPrecio.setPreferredSize(new java.awt.Dimension(170, 62));
        jPanelJavaFlixEstandarPrecio.setRequestFocusEnabled(false);
        jPanelJavaFlixEstandarPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelJavaFlixEstandarPrecioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelJavaFlixEstandarPrecioMouseExited(evt);
            }
        });

        jLabelJavaFlixEstandarPrecio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelJavaFlixEstandarPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJavaFlixEstandarPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJavaFlixEstandarPrecio.setText("11,99€");
        jLabelJavaFlixEstandarPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelJavaFlixEstandarPrecioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelJavaFlixEstandarPrecioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelJavaFlixEstandarPrecioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelJavaFlixEstandarPrecioLayout = new javax.swing.GroupLayout(jPanelJavaFlixEstandarPrecio);
        jPanelJavaFlixEstandarPrecio.setLayout(jPanelJavaFlixEstandarPrecioLayout);
        jPanelJavaFlixEstandarPrecioLayout.setHorizontalGroup(
            jPanelJavaFlixEstandarPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJavaFlixEstandarPrecioLayout.createSequentialGroup()
                .addComponent(jLabelJavaFlixEstandarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelJavaFlixEstandarPrecioLayout.setVerticalGroup(
            jPanelJavaFlixEstandarPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelJavaFlixEstandarPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelIntroDatos.add(jPanelJavaFlixEstandarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 130, 60));

        jLabelJavaFlixPremium.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabelJavaFlixPremium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJavaFlixPremium.setText("JavaFlix Premium\n");
        jPanelIntroDatos.add(jLabelJavaFlixPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 410, -1));

        jPanelJavaFlixPremiumPrecio.setBackground(new java.awt.Color(180, 45, 49));
        jPanelJavaFlixPremiumPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelJavaFlixPremiumPrecio.setPreferredSize(new java.awt.Dimension(170, 62));
        jPanelJavaFlixPremiumPrecio.setRequestFocusEnabled(false);
        jPanelJavaFlixPremiumPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelJavaFlixPremiumPrecioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelJavaFlixPremiumPrecioMouseExited(evt);
            }
        });
        jPanelJavaFlixPremiumPrecio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelJavaFlixPremiumPrecio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelJavaFlixPremiumPrecio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelJavaFlixPremiumPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJavaFlixPremiumPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJavaFlixPremiumPrecio.setText("15,99€\n");
        jLabelJavaFlixPremiumPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelJavaFlixPremiumPrecioMouseClicked(evt);
            }
        });
        jPanelJavaFlixPremiumPrecio.add(jLabelJavaFlixPremiumPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        jLabelFondoPremiun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondoPremiun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/imagendorado.png"))); // NOI18N
        jPanelJavaFlixPremiumPrecio.add(jLabelFondoPremiun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        jPanelIntroDatos.add(jPanelJavaFlixPremiumPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 130, 60));

        jPanelventana.add(jPanelIntroDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 410, 710));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/palomitasbienrojo.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel2");
        jPanelventana.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1239, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelventana, javax.swing.GroupLayout.PREFERRED_SIZE, 1239, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelventana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        UtilJavaflix.guardarDatos();
        this.padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        // TODO add your handling code here:
        jPanelCerrar.setBackground(new Color(232, 17, 35));
        jLabelCerrar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        // TODO add your handling code here:
        jPanelCerrar.setBackground(new Color(255, 255, 255));
        jLabelCerrar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void jPanelAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseEntered
        // TODO add your handling code here:
        jPanelAtras.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_jPanelAtrasMouseEntered

    private void jPanelAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseExited
        // TODO add your handling code here:
        jPanelAtras.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jPanelAtrasMouseExited

    private void jPanelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_jPanelAtrasMouseClicked

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        // TODO add your handling code here:      
        UtilJavaflix.cerrarPrograma();

    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void jPanelJavaFlixBasicoPrecioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJavaFlixBasicoPrecioMouseEntered
        // TODO add your handling code here:
        jPanelJavaFlixBasicoPrecio.setBackground(new Color(126, 16, 27));
    }//GEN-LAST:event_jPanelJavaFlixBasicoPrecioMouseEntered

    private void jPanelJavaFlixEstandarPrecioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJavaFlixEstandarPrecioMouseEntered
        // TODO add your handling code here:
        jPanelJavaFlixEstandarPrecio.setBackground(new Color(126, 16, 27));
        
    }//GEN-LAST:event_jPanelJavaFlixEstandarPrecioMouseEntered

    private void jPanelJavaFlixPremiumPrecioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJavaFlixPremiumPrecioMouseEntered
        // TODO add your handling code here:
        jLabelFondoPremiun.setVisible(false);
    }//GEN-LAST:event_jPanelJavaFlixPremiumPrecioMouseEntered

    private void jPanelJavaFlixBasicoPrecioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJavaFlixBasicoPrecioMouseExited
        // TODO add your handling code here:
        jPanelJavaFlixBasicoPrecio.setBackground(new Color(180, 45, 49));
    }//GEN-LAST:event_jPanelJavaFlixBasicoPrecioMouseExited

    private void jPanelJavaFlixEstandarPrecioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJavaFlixEstandarPrecioMouseExited
        // TODO add your handling code here:
        jPanelJavaFlixEstandarPrecio.setBackground(new Color(180, 45, 49));
    }//GEN-LAST:event_jPanelJavaFlixEstandarPrecioMouseExited

    private void jPanelJavaFlixPremiumPrecioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJavaFlixPremiumPrecioMouseExited
        // TODO add your handling code here:
        jLabelFondoPremiun.setVisible(true);
    }//GEN-LAST:event_jPanelJavaFlixPremiumPrecioMouseExited

    private void jLabelJavaFlixBasicoPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJavaFlixBasicoPrecioMouseClicked
        // TODO add your handling code here:
        PlanSuscripcion plannuevo = new PlanSuscripcion("Basico", LocalDate.now());
        Cliente nuevocliente = new Cliente(this.dni, this.nombre, this.tarjeta, plannuevo, this.pass, this.email  );
        plannuevo.setCliente(nuevocliente);
        JOptionPane.showMessageDialog(rootPane, "Usuario registrado correctamente", "Registro completado", JOptionPane.INFORMATION_MESSAGE);
        UtilJavaflix.addCliente(nuevocliente);
        UtilJavaflix.guardarDatos();
        UtilJavaflix.generarFactura(plannuevo,8.99);
        this.dispose();
        this.padre.dispose();
        this.padre.getPadre().setVisible(true);
    }//GEN-LAST:event_jLabelJavaFlixBasicoPrecioMouseClicked

    private void jLabelJavaFlixEstandarPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJavaFlixEstandarPrecioMouseClicked
        // TODO add your handling code here:
        PlanSuscripcion plannuevo = new PlanSuscripcion("Estandar", LocalDate.now());
        Cliente nuevocliente = new Cliente(this.dni, this.nombre, this.tarjeta, plannuevo, this.pass, this.email  );
        plannuevo.setCliente(nuevocliente);
        JOptionPane.showMessageDialog(rootPane, "Usuario registrado correctamente", "Registro completado", JOptionPane.INFORMATION_MESSAGE);
        UtilJavaflix.addCliente(nuevocliente);
        UtilJavaflix.guardarDatos();
        UtilJavaflix.generarFactura(plannuevo,11.99);
        this.dispose();
        this.padre.getPadre().setVisible(true);
    }//GEN-LAST:event_jLabelJavaFlixEstandarPrecioMouseClicked

    private void jLabelJavaFlixPremiumPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJavaFlixPremiumPrecioMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        PlanSuscripcion plannuevo = new PlanSuscripcion("Premium", LocalDate.now());
        Cliente nuevocliente = new Cliente(this.dni, this.nombre, this.tarjeta, plannuevo, this.pass, this.email  );
        plannuevo.setCliente(nuevocliente);
        JOptionPane.showMessageDialog(rootPane, "Usuario registrado correctamente", "Registro completado", JOptionPane.INFORMATION_MESSAGE);
        UtilJavaflix.addCliente(nuevocliente);
        UtilJavaflix.guardarDatos();
        UtilJavaflix.generarFactura(plannuevo,15.99);
        this.dispose();
        this.padre.getPadre().setVisible(true);
    }//GEN-LAST:event_jLabelJavaFlixPremiumPrecioMouseClicked

    private void jLabelJavaFlixBasicoPrecioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJavaFlixBasicoPrecioMouseEntered
        // TODO add your handling code here:
        jPanelJavaFlixBasicoPrecio.setBackground(new Color(148, 13, 30));
    }//GEN-LAST:event_jLabelJavaFlixBasicoPrecioMouseEntered

    private void jLabelJavaFlixBasicoPrecioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJavaFlixBasicoPrecioMouseExited
        // TODO add your handling code here:
        jPanelJavaFlixBasicoPrecio.setBackground(new Color(180, 45, 49));
    }//GEN-LAST:event_jLabelJavaFlixBasicoPrecioMouseExited

    private void jLabelJavaFlixEstandarPrecioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJavaFlixEstandarPrecioMouseEntered
        // TODO add your handling code here:
        jPanelJavaFlixEstandarPrecio.setBackground(new Color(148, 13, 30));
    }//GEN-LAST:event_jLabelJavaFlixEstandarPrecioMouseEntered

    private void jLabelJavaFlixEstandarPrecioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJavaFlixEstandarPrecioMouseExited
        // TODO add your handling code here:
        jPanelJavaFlixEstandarPrecio.setBackground(new Color(180, 45, 49));
    }//GEN-LAST:event_jLabelJavaFlixEstandarPrecioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelAtras;
    private javax.swing.JLabel jLabelCREATUCUENTA;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelDoblez;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoEtiquetas;
    private javax.swing.JLabel jLabelFondoPremiun;
    private javax.swing.JLabel jLabelJAVAFLIX;
    private javax.swing.JLabel jLabelJAVAFLIXSombra;
    private javax.swing.JLabel jLabelJavaFlixBasico;
    private javax.swing.JLabel jLabelJavaFlixBasicoPrecio;
    private javax.swing.JLabel jLabelJavaFlixEstandar;
    private javax.swing.JLabel jLabelJavaFlixEstandarPrecio;
    private javax.swing.JLabel jLabelJavaFlixPremium;
    private javax.swing.JLabel jLabelJavaFlixPremiumPrecio;
    private javax.swing.JPanel jPanelAtras;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelIntroDatos;
    private javax.swing.JPanel jPanelJavaFlixBasicoPrecio;
    private javax.swing.JPanel jPanelJavaFlixEstandarPrecio;
    private javax.swing.JPanel jPanelJavaFlixPremiumPrecio;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelventana;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
