/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.TarjetaCredito;
import java.awt.Color;
import Clases.UtilJavaflix;
import Excepciones.EmailNoValido;
import Excepciones.EmailYaExistente;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class registroUsuario extends javax.swing.JFrame {

    private ventanaPrincipal padre;

    public ventanaPrincipal getPadre() {
        return padre;
    }
    
    /**
     * Creates new form ventanaPrincipal
     */
    public registroUsuario(ventanaPrincipal main) {
        padre = main;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelventana = new javax.swing.JPanel();
        jPanelOpciones = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        jLabelCerrarRegistro = new javax.swing.JLabel();
        jPanelAtras = new javax.swing.JPanel();
        jLabelAtrasRegistro = new javax.swing.JLabel();
        jLabelCREATUCUENTA = new javax.swing.JLabel();
        jLabelDEJAVAFLIX = new javax.swing.JLabel();
        jLabelDoblez = new javax.swing.JLabel();
        jLabelFondoEtiquetas = new javax.swing.JLabel();
        jLabelJAVAFLIX = new javax.swing.JLabel();
        jLabelJAVAFLIXSombra = new javax.swing.JLabel();
        jPanelRegistrarse = new javax.swing.JPanel();
        jLabelRegistrarsebuttom = new javax.swing.JLabel();
        jPanelIntroDatos = new javax.swing.JPanel();
        jTextFieldbug = new javax.swing.JTextField();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jSeparatorDNI = new javax.swing.JSeparator();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jSeparatorNombre = new javax.swing.JSeparator();
        jLabelNumTarjeta = new javax.swing.JLabel();
        jTextFieldCE = new javax.swing.JTextField();
        jSeparatorClave = new javax.swing.JSeparator();
        jLabelCaducidad = new javax.swing.JLabel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelClave = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();
        jLabelDATOSBANCARIOS = new javax.swing.JLabel();
        jSeparatorNumTarjeta = new javax.swing.JSeparator();
        jSeparatorCaducidad = new javax.swing.JSeparator();
        jSeparatorSaldo = new javax.swing.JSeparator();
        jSeparatorCE = new javax.swing.JSeparator();
        jLabelCE = new javax.swing.JLabel();
        jPasswordFieldClave = new javax.swing.JPasswordField();
        jFormattedTextFieldFechaCaducidad = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNumTarjeta = new javax.swing.JFormattedTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1239, 725));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });
        jPanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrarRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCerrarRegistro.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabelCerrarRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrarRegistro.setText("X");
        jPanelCerrar.add(jLabelCerrarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanelOpciones.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanelAtras.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseExited(evt);
            }
        });
        jPanelAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAtrasRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAtrasRegistro.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabelAtrasRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAtrasRegistro.setText("< ");
        jPanelAtras.add(jLabelAtrasRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        jPanelOpciones.add(jPanelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 30));

        jPanelventana.add(jPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabelCREATUCUENTA.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabelCREATUCUENTA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCREATUCUENTA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCREATUCUENTA.setText("CREA TU CUENTA");
        jPanelventana.add(jLabelCREATUCUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 430, 70));

        jLabelDEJAVAFLIX.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabelDEJAVAFLIX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDEJAVAFLIX.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDEJAVAFLIX.setText("DE JAVAFLIX");
        jPanelventana.add(jLabelDEJAVAFLIX, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 410, 70));

        jLabelDoblez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/doblez.jpg"))); // NOI18N
        jPanelventana.add(jLabelDoblez, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 30, -1));

        jLabelFondoEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoetiquetas.jpg"))); // NOI18N
        jLabelFondoEtiquetas.setText("jLabel7");
        jPanelventana.add(jLabelFondoEtiquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 440, 120));

        jLabelJAVAFLIX.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJAVAFLIX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIX.setText("JAVAFLIX");
        jPanelventana.add(jLabelJAVAFLIX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, 130));

        jLabelJAVAFLIXSombra.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIXSombra.setForeground(new java.awt.Color(112, 101, 101));
        jLabelJAVAFLIXSombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIXSombra.setText("JAVAFLIX");
        jPanelventana.add(jLabelJAVAFLIXSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 810, 130));

        jPanelRegistrarse.setBackground(new java.awt.Color(180, 45, 49));
        jPanelRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRegistrarse.setPreferredSize(new java.awt.Dimension(170, 62));
        jPanelRegistrarse.setRequestFocusEnabled(false);
        jPanelRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRegistrarseMouseEntered(evt);
            }
        });

        jLabelRegistrarsebuttom.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabelRegistrarsebuttom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarsebuttom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistrarsebuttom.setText("REGISTRARSE");
        jLabelRegistrarsebuttom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistrarsebuttom.setFocusable(false);
        jLabelRegistrarsebuttom.setMaximumSize(new java.awt.Dimension(62, 17));
        jLabelRegistrarsebuttom.setMinimumSize(new java.awt.Dimension(62, 17));
        jLabelRegistrarsebuttom.setName(""); // NOI18N
        jLabelRegistrarsebuttom.setPreferredSize(new java.awt.Dimension(62, 17));
        jLabelRegistrarsebuttom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrarsebuttomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRegistrarsebuttomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRegistrarsebuttomMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrarseLayout = new javax.swing.GroupLayout(jPanelRegistrarse);
        jPanelRegistrarse.setLayout(jPanelRegistrarseLayout);
        jPanelRegistrarseLayout.setHorizontalGroup(
            jPanelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRegistrarsebuttom, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanelRegistrarseLayout.setVerticalGroup(
            jPanelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRegistrarsebuttom, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jPanelventana.add(jPanelRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 240, 90));

        jPanelIntroDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelIntroDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldbug.setText("jTextField1");
        jPanelIntroDatos.add(jTextFieldbug, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        jLabelDNI.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelDNI.setText("DNI");
        jPanelIntroDatos.add(jLabelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 300, -1));

        jTextFieldDNI.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTextFieldDNI.setForeground(java.awt.Color.gray);
        jTextFieldDNI.setText("Escriba su DNI");
        jTextFieldDNI.setToolTipText("");
        jTextFieldDNI.setBorder(null);
        jTextFieldDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDNIFocusGained(evt);
            }
        });
        jTextFieldDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldDNIMousePressed(evt);
            }
        });
        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });
        jPanelIntroDatos.add(jTextFieldDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 300, 20));
        jPanelIntroDatos.add(jSeparatorDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 310, 20));

        jLabelNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelNombre.setText("NOMBRE");
        jPanelIntroDatos.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 300, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTextFieldNombre.setForeground(java.awt.Color.gray);
        jTextFieldNombre.setText("Escriba su nombre");
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusGained(evt);
            }
        });
        jTextFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNombreMousePressed(evt);
            }
        });
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanelIntroDatos.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 300, 20));
        jPanelIntroDatos.add(jSeparatorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 310, 20));

        jLabelNumTarjeta.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelNumTarjeta.setText("Nº TARJETA (####-####-####-####)");
        jPanelIntroDatos.add(jLabelNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 300, -1));

        jTextFieldCE.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTextFieldCE.setForeground(java.awt.Color.gray);
        jTextFieldCE.setText("Escriba su correo electrónico");
        jTextFieldCE.setBorder(null);
        jTextFieldCE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCEFocusGained(evt);
            }
        });
        jTextFieldCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldCEMousePressed(evt);
            }
        });
        jPanelIntroDatos.add(jTextFieldCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 300, 20));
        jPanelIntroDatos.add(jSeparatorClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 310, 20));

        jLabelCaducidad.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelCaducidad.setText("CADUCIDAD (YYYY-MM-DD)");
        jPanelIntroDatos.add(jLabelCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 300, -1));

        jLabelSaldo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelSaldo.setText("SALDO");
        jPanelIntroDatos.add(jLabelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 300, -1));

        jLabelClave.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelClave.setText("CLAVE");
        jPanelIntroDatos.add(jLabelClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 300, 20));

        jTextFieldSaldo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTextFieldSaldo.setForeground(java.awt.Color.gray);
        jTextFieldSaldo.setText("Escriba su saldo");
        jTextFieldSaldo.setBorder(null);
        jTextFieldSaldo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSaldoFocusGained(evt);
            }
        });
        jTextFieldSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldSaldoMousePressed(evt);
            }
        });
        jPanelIntroDatos.add(jTextFieldSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 300, 20));

        jLabelDATOSBANCARIOS.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelDATOSBANCARIOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDATOSBANCARIOS.setText("DATOS BANCARIOS");
        jPanelIntroDatos.add(jLabelDATOSBANCARIOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 410, -1));
        jPanelIntroDatos.add(jSeparatorNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 310, 20));
        jPanelIntroDatos.add(jSeparatorCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 310, 20));
        jPanelIntroDatos.add(jSeparatorSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 310, 20));
        jPanelIntroDatos.add(jSeparatorCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 310, 20));

        jLabelCE.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelCE.setText("CORREO ELECTRÓNICO");
        jPanelIntroDatos.add(jLabelCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 300, 20));

        jPasswordFieldClave.setForeground(java.awt.Color.gray);
        jPasswordFieldClave.setText("**********");
        jPasswordFieldClave.setBorder(null);
        jPasswordFieldClave.setCaretPosition(0);
        jPasswordFieldClave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldClaveFocusGained(evt);
            }
        });
        jPasswordFieldClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldClaveMousePressed(evt);
            }
        });
        jPanelIntroDatos.add(jPasswordFieldClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 300, 20));

        jFormattedTextFieldFechaCaducidad.setBorder(null);
        jFormattedTextFieldFechaCaducidad.setColumns(16);
        try {
            jFormattedTextFieldFechaCaducidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFechaCaducidad.setToolTipText("");
        jFormattedTextFieldFechaCaducidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldFechaCaducidadFocusGained(evt);
            }
        });
        jFormattedTextFieldFechaCaducidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFormattedTextFieldFechaCaducidadMousePressed(evt);
            }
        });
        jPanelIntroDatos.add(jFormattedTextFieldFechaCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 300, 20));

        jFormattedTextFieldNumTarjeta.setBorder(null);
        jFormattedTextFieldNumTarjeta.setColumns(16);
        try {
            jFormattedTextFieldNumTarjeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNumTarjeta.setToolTipText("");
        jFormattedTextFieldNumTarjeta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldNumTarjetaFocusGained(evt);
            }
        });
        jFormattedTextFieldNumTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFormattedTextFieldNumTarjetaMousePressed(evt);
            }
        });
        jPanelIntroDatos.add(jFormattedTextFieldNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 300, 20));

        jPanelventana.add(jPanelIntroDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 410, 710));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/palomitasbienrojo.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel2");
        jPanelventana.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1239, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelventana, javax.swing.GroupLayout.PREFERRED_SIZE, 1239, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelventana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    private void jLabelRegistrarsebuttomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrarsebuttomMouseClicked
        try {
            // Hacemos esto para validar los dos campos 
            String email = jTextFieldCE.getText();
            UtilJavaflix.validarEmail(email);
            if (UtilJavaflix.existenteEmailRegistrado(email)){
                throw new EmailYaExistente("El email introduco ya esta registrado");
            }
            LocalDate fechacaducidad = LocalDate.parse(jFormattedTextFieldFechaCaducidad.getText());
            TarjetaCredito nuevatarjeta = new TarjetaCredito(jFormattedTextFieldNumTarjeta.getText(), fechacaducidad,
                    Double.parseDouble(jTextFieldSaldo.getText()));
            System.out.println(nuevatarjeta);
            planregistroUsuario nuevocliente = new planregistroUsuario(this, jTextFieldDNI.getText(), jTextFieldNombre.getText(),
                    email, String.valueOf(jPasswordFieldClave.getPassword()), nuevatarjeta);
            this.dispose();
        } catch (EmailNoValido | EmailYaExistente ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR: Formato de fecha invalido (Usar yyyy-dd-MM)", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelRegistrarsebuttomMouseClicked

    private void jLabelRegistrarsebuttomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrarsebuttomMouseEntered
        // TODO add your handling code here:
        jPanelRegistrarse.setBackground(new Color(148, 13, 30));
    }//GEN-LAST:event_jLabelRegistrarsebuttomMouseEntered

    private void jLabelRegistrarsebuttomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrarsebuttomMouseExited
        // TODO add your handling code here:
        jPanelRegistrarse.setBackground(new Color(180, 45, 49));
    }//GEN-LAST:event_jLabelRegistrarsebuttomMouseExited

    private void jTextFieldDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDNIMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNIMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        UtilJavaflix.guardarDatos();
        this.padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jPanelRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRegistrarseMouseEntered
        // TODO add your handling code here:
        jPanelRegistrarse.setOpaque(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jPanelRegistrarseMouseEntered

    private void jTextFieldNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreMousePressed

    private void jTextFieldCEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCEMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEMousePressed

    private void jPasswordFieldClaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldClaveMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldClaveMousePressed

    private void jTextFieldSaldoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSaldoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(jTextFieldSaldo.getText()).equals("Escriba su saldo")) {
            jTextFieldSaldo.setText("");
            jTextFieldSaldo.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldSaldoMousePressed

    private void jFormattedTextFieldFechaCaducidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFechaCaducidadMousePressed
        if (jTextFieldSaldo.getText().isEmpty()) {
            jTextFieldSaldo.setText("Escriba su saldo");
            jTextFieldSaldo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jFormattedTextFieldFechaCaducidadMousePressed

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        // TODO add your handling code here:
        jPanelCerrar.setBackground(new Color(232, 17, 35));
        jLabelCerrarRegistro.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        // TODO add your handling code here:
        jPanelCerrar.setBackground(new Color(255, 255, 255));
        jLabelCerrarRegistro.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void jPanelAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseEntered
        // TODO add your handling code here:
        jPanelAtras.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_jPanelAtrasMouseEntered

    private void jPanelAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseExited
        // TODO add your handling code here:
        jPanelAtras.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jPanelAtrasMouseExited

    private void jPanelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_jPanelAtrasMouseClicked

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        // TODO add your handling code here:      
        UtilJavaflix.cerrarPrograma();

    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void jFormattedTextFieldNumTarjetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNumTarjetaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldNumTarjetaMousePressed

    private void jTextFieldDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDNIFocusGained
        // TODO add your handling code here:
        if (jTextFieldDNI.getText().equals("Escriba su DNI")) {
            jTextFieldDNI.setText("");
            jTextFieldDNI.setForeground(Color.black);
        }
        if (String.valueOf(jPasswordFieldClave.getPassword()).isEmpty()) {
            jPasswordFieldClave.setText("**********");
            jPasswordFieldClave.setForeground(Color.gray);
        }
        if (jTextFieldNombre.getText().isEmpty()) {
            jTextFieldNombre.setText("Escriba su nombre");
            jTextFieldNombre.setForeground(Color.gray);
        }
        if (jTextFieldCE.getText().isEmpty()) {
            jTextFieldCE.setText("Escriba su correo electrónico");
            jTextFieldCE.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextFieldDNIFocusGained

    private void jTextFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusGained
        // TODO add your handling code here:
        if (jTextFieldNombre.getText().equals("Escriba su nombre")) {
            jTextFieldNombre.setText("");
            jTextFieldNombre.setForeground(Color.black);
        }
        if (jTextFieldDNI.getText().isEmpty()) {
            jTextFieldDNI.setText("Escriba su DNI");
            jTextFieldDNI.setForeground(Color.gray);
        }
        if (jTextFieldCE.getText().isEmpty()) {
            jTextFieldCE.setText("Escriba su correo electrónico");
            jTextFieldCE.setForeground(Color.gray);
        }
        if (String.valueOf(jPasswordFieldClave.getPassword()).isEmpty()) {
            jPasswordFieldClave.setText("**********");
            jPasswordFieldClave.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextFieldNombreFocusGained

    private void jTextFieldCEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCEFocusGained
        // TODO add your handling code here:
        if (jTextFieldCE.getText().equals("Escriba su correo electrónico")) {
            jTextFieldCE.setText("");
            jTextFieldCE.setForeground(Color.black);
        }
        if (jTextFieldDNI.getText().isEmpty()) {
            jTextFieldDNI.setText("Escriba su DNI");
            jTextFieldDNI.setForeground(Color.gray);
        }
        if (jTextFieldNombre.getText().isEmpty()) {
            jTextFieldNombre.setText("Escriba su nombre");
            jTextFieldNombre.setForeground(Color.gray);
        }
        if (String.valueOf(jPasswordFieldClave.getPassword()).isEmpty()) {
            jPasswordFieldClave.setText("**********");
            jPasswordFieldClave.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextFieldCEFocusGained

    private void jPasswordFieldClaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldClaveFocusGained
        // TODO add your handling code here:
        if (String.valueOf(jPasswordFieldClave.getPassword()).equals("**********")) {
            jPasswordFieldClave.setText("");
            jPasswordFieldClave.setForeground(Color.black);
        }
        if (jTextFieldDNI.getText().isEmpty()) {
            jTextFieldDNI.setText("Escriba su DNI");
            jTextFieldDNI.setForeground(Color.gray);
        }
        if (jTextFieldNombre.getText().isEmpty()) {
            jTextFieldNombre.setText("Escriba su nombre");
            jTextFieldNombre.setForeground(Color.gray);
        }
        if (jTextFieldCE.getText().isEmpty()) {
            jTextFieldCE.setText("Escriba su correo electrónico");
            jTextFieldCE.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPasswordFieldClaveFocusGained

    private void jFormattedTextFieldNumTarjetaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNumTarjetaFocusGained
        // TODO add your handling code here:
        if (jFormattedTextFieldNumTarjeta.getText().equals("")){
            jFormattedTextFieldNumTarjeta.setText("");
            jFormattedTextFieldNumTarjeta.setForeground(Color.black);
        }
        if (jFormattedTextFieldFechaCaducidad.getText().isEmpty()) {
            jFormattedTextFieldFechaCaducidad.setText("");
            jFormattedTextFieldFechaCaducidad.setForeground(Color.gray);
        }
        if (jTextFieldSaldo.getText().isEmpty()) {
            jTextFieldSaldo.setText("Escriba su saldo");
            jTextFieldSaldo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jFormattedTextFieldNumTarjetaFocusGained

    private void jFormattedTextFieldFechaCaducidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFechaCaducidadFocusGained
        // TODO add your handling code here:
        if (jFormattedTextFieldFechaCaducidad.getText().equals("")){
            jFormattedTextFieldFechaCaducidad.setText("");
            jFormattedTextFieldFechaCaducidad.setForeground(Color.black);
        }
        if (jFormattedTextFieldNumTarjeta.getText().isEmpty()) {
            jFormattedTextFieldNumTarjeta.setText("");
            jFormattedTextFieldNumTarjeta.setForeground(Color.gray);
        }
        if (jTextFieldSaldo.getText().isEmpty()) {
            jTextFieldSaldo.setText("Escriba su saldo");
            jTextFieldSaldo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jFormattedTextFieldFechaCaducidadFocusGained

    private void jTextFieldSaldoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSaldoFocusGained
        // TODO add your handling code here:
        if (jTextFieldSaldo.getText().equals("Escriba su saldo")){
            jTextFieldSaldo.setText("");
            jTextFieldSaldo.setForeground(Color.black);
        }
        if (jFormattedTextFieldFechaCaducidad.getText().isEmpty()) {
            jFormattedTextFieldFechaCaducidad.setText("");
            jFormattedTextFieldFechaCaducidad.setForeground(Color.gray);
        }
        if (jFormattedTextFieldNumTarjeta.getText().isEmpty()) {
            jFormattedTextFieldNumTarjeta.setText("");
            jFormattedTextFieldNumTarjeta.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextFieldSaldoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jFormattedTextFieldFechaCaducidad;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumTarjeta;
    private javax.swing.JLabel jLabelAtrasRegistro;
    private javax.swing.JLabel jLabelCE;
    private javax.swing.JLabel jLabelCREATUCUENTA;
    private javax.swing.JLabel jLabelCaducidad;
    private javax.swing.JLabel jLabelCerrarRegistro;
    private javax.swing.JLabel jLabelClave;
    private javax.swing.JLabel jLabelDATOSBANCARIOS;
    private javax.swing.JLabel jLabelDEJAVAFLIX;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDoblez;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoEtiquetas;
    private javax.swing.JLabel jLabelJAVAFLIX;
    private javax.swing.JLabel jLabelJAVAFLIXSombra;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumTarjeta;
    private javax.swing.JLabel jLabelRegistrarsebuttom;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JPanel jPanelAtras;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelIntroDatos;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelRegistrarse;
    private javax.swing.JPanel jPanelventana;
    private javax.swing.JPasswordField jPasswordFieldClave;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparatorCE;
    private javax.swing.JSeparator jSeparatorCaducidad;
    private javax.swing.JSeparator jSeparatorClave;
    private javax.swing.JSeparator jSeparatorDNI;
    private javax.swing.JSeparator jSeparatorNombre;
    private javax.swing.JSeparator jSeparatorNumTarjeta;
    private javax.swing.JSeparator jSeparatorSaldo;
    private javax.swing.JTextField jTextFieldCE;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextFieldbug;
    // End of variables declaration//GEN-END:variables
}
