/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Cliente;

import java.awt.Color;

import Clases.UtilJavaflix;
import Excepciones.EmailNoEncontrado;
import Excepciones.EmailNoValido;
import Excepciones.PasswordIncorrecta;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        UtilJavaflix.cargarDatos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelventana = new javax.swing.JPanel();
        jPanelOpciones = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelJAVAFLIX = new javax.swing.JLabel();
        jLabelJAVAFLIXSombra = new javax.swing.JLabel();
        jLabelINICIARSESION = new javax.swing.JLabel();
        jLabelFondoEtiquetas = new javax.swing.JLabel();
        jLabelDoblez = new javax.swing.JLabel();
        jPanelIntroDatos = new javax.swing.JPanel();
        jLabelCE = new javax.swing.JLabel();
        jTextFieldDebug = new javax.swing.JTextField();
        jTextFieldCE = new javax.swing.JTextField();
        jSeparatorCE = new javax.swing.JSeparator();
        jLabelClave = new javax.swing.JLabel();
        jPasswordFieldClave = new javax.swing.JPasswordField();
        jSeparatorClave = new javax.swing.JSeparator();
        jPanelAcceder = new javax.swing.JPanel();
        jLabelAccederbuttom = new javax.swing.JLabel();
        jLabelNotienescuenta = new javax.swing.JLabel();
        jPanelRegistrarse = new javax.swing.JPanel();
        jLabelRegistrarsebuttom = new javax.swing.JLabel();
        jLabelFondoAcceso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });
        jPanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("X");
        jPanelCerrar.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanelOpciones.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanelventana.add(jPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jLabelJAVAFLIX.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJAVAFLIX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIX.setText("JAVAFLIX");
        jPanelventana.add(jLabelJAVAFLIX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, 130));

        jLabelJAVAFLIXSombra.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIXSombra.setForeground(new java.awt.Color(112, 101, 101));
        jLabelJAVAFLIXSombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIXSombra.setText("JAVAFLIX");
        jPanelventana.add(jLabelJAVAFLIXSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 810, 130));

        jLabelINICIARSESION.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabelINICIARSESION.setForeground(new java.awt.Color(255, 255, 255));
        jLabelINICIARSESION.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelINICIARSESION.setText("INICIAR SESIÓN");
        jPanelventana.add(jLabelINICIARSESION, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 440, 120));

        jLabelFondoEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoetiquetas.jpg"))); // NOI18N
        jLabelFondoEtiquetas.setText("jLabel7");
        jPanelventana.add(jLabelFondoEtiquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 440, 120));

        jLabelDoblez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/doblez.jpg"))); // NOI18N
        jPanelventana.add(jLabelDoblez, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 30, -1));

        jPanelIntroDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelIntroDatos.setMinimumSize(new java.awt.Dimension(360, 520));
        jPanelIntroDatos.setName(""); // NOI18N
        jPanelIntroDatos.setPreferredSize(new java.awt.Dimension(360, 582));
        jPanelIntroDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCE.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelCE.setText("CORREO ELECTRÓNICO");
        jPanelIntroDatos.add(jLabelCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jTextFieldDebug.setText("jTextField1");
        jPanelIntroDatos.add(jTextFieldDebug, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jTextFieldCE.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTextFieldCE.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCE.setText("Escriba su correo electrónico");
        jTextFieldCE.setToolTipText("");
        jTextFieldCE.setBorder(null);
        jTextFieldCE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCEFocusGained(evt);
            }
        });
        jTextFieldCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldCEMousePressed(evt);
            }
        });
        jTextFieldCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCEActionPerformed(evt);
            }
        });
        jPanelIntroDatos.add(jTextFieldCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 300, -1));
        jPanelIntroDatos.add(jSeparatorCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 310, 18));

        jLabelClave.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelClave.setText("CLAVE");
        jPanelIntroDatos.add(jLabelClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jPasswordFieldClave.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordFieldClave.setText("**********");
        jPasswordFieldClave.setToolTipText("");
        jPasswordFieldClave.setBorder(null);
        jPasswordFieldClave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldClaveFocusGained(evt);
            }
        });
        jPasswordFieldClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldClaveMousePressed(evt);
            }
        });
        jPasswordFieldClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldClaveActionPerformed(evt);
            }
        });
        jPanelIntroDatos.add(jPasswordFieldClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 290, -1));
        jPanelIntroDatos.add(jSeparatorClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 310, 20));

        jPanelAcceder.setBackground(new java.awt.Color(180, 45, 49));
        jPanelAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelAccederbuttom.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabelAccederbuttom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAccederbuttom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAccederbuttom.setText("ACCEDER");
        jLabelAccederbuttom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAccederbuttom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAccederbuttomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAccederbuttomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAccederbuttomMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelAccederbuttomMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAccederbuttomMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelAccederLayout = new javax.swing.GroupLayout(jPanelAcceder);
        jPanelAcceder.setLayout(jPanelAccederLayout);
        jPanelAccederLayout.setHorizontalGroup(
            jPanelAccederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAccederbuttom, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanelAccederLayout.setVerticalGroup(
            jPanelAccederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAccederbuttom, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        jPanelIntroDatos.add(jPanelAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 170, -1));

        jLabelNotienescuenta.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelNotienescuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNotienescuenta.setText("¿No tienes cuenta? Registrate");
        jPanelIntroDatos.add(jLabelNotienescuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 410, -1));

        jPanelRegistrarse.setBackground(new java.awt.Color(180, 45, 49));
        jPanelRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRegistrarse.setPreferredSize(new java.awt.Dimension(170, 62));
        jPanelRegistrarse.setRequestFocusEnabled(false);

        jLabelRegistrarsebuttom.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabelRegistrarsebuttom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarsebuttom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistrarsebuttom.setText("REGISTRASRE");
        jLabelRegistrarsebuttom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistrarsebuttom.setMaximumSize(new java.awt.Dimension(62, 17));
        jLabelRegistrarsebuttom.setMinimumSize(new java.awt.Dimension(62, 17));
        jLabelRegistrarsebuttom.setName(""); // NOI18N
        jLabelRegistrarsebuttom.setPreferredSize(new java.awt.Dimension(62, 17));
        jLabelRegistrarsebuttom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrarsebuttomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRegistrarsebuttomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRegistrarsebuttomMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrarseLayout = new javax.swing.GroupLayout(jPanelRegistrarse);
        jPanelRegistrarse.setLayout(jPanelRegistrarseLayout);
        jPanelRegistrarseLayout.setHorizontalGroup(
            jPanelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRegistrarsebuttom, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanelRegistrarseLayout.setVerticalGroup(
            jPanelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRegistrarsebuttom, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        jPanelIntroDatos.add(jPanelRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 170, -1));

        jPanelventana.add(jPanelIntroDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 410, 640));

        jLabelFondoAcceso.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondoAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/palomitasbienrojo.jpg"))); // NOI18N
        jLabelFondoAcceso.setText("jLabel2");
        jPanelventana.add(jLabelFondoAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1239, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelventana, javax.swing.GroupLayout.PREFERRED_SIZE, 1239, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelventana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAccederbuttomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederbuttomMouseClicked
        // TODO add your handling code here:
        
        try {
            UtilJavaflix.validarEmail(jTextFieldCE.getText());
            if (UtilJavaflix.checkAdminlogin(jTextFieldCE.getText(),String.valueOf(jPasswordFieldClave.getPassword()))){
                this.dispose();
                ventanaAdmin ventanaAdmin = new ventanaAdmin(this);
            } else {
            Cliente cliente_logeado = UtilJavaflix.iniciarSesion(jTextFieldCE.getText(),String.valueOf(jPasswordFieldClave.getPassword()));
            entradaUsuario principal = new entradaUsuario(this, cliente_logeado);
            this.dispose();
            }
        } catch (EmailNoValido | EmailNoEncontrado | PasswordIncorrecta ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelAccederbuttomMouseClicked

    private void jTextFieldCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEActionPerformed

    private void jLabelRegistrarsebuttomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrarsebuttomMouseClicked
        this.setVisible(false);
        registroUsuario registro = new registroUsuario(this);
        registro.setVisible(true);
    }//GEN-LAST:event_jLabelRegistrarsebuttomMouseClicked

    private void jLabelAccederbuttomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederbuttomMouseEntered
        // TODO add your handling code here:   
        jPanelAcceder.setBackground(new Color(148, 13, 30));
    }//GEN-LAST:event_jLabelAccederbuttomMouseEntered

    private void jLabelAccederbuttomMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederbuttomMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelAccederbuttomMouseReleased

    private void jLabelAccederbuttomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederbuttomMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelAccederbuttomMousePressed

    private void jLabelAccederbuttomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederbuttomMouseExited
        // TODO add your handling code here:
        jPanelAcceder.setBackground(new Color(180, 45, 49));
    }//GEN-LAST:event_jLabelAccederbuttomMouseExited

    private void jLabelRegistrarsebuttomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrarsebuttomMouseEntered
        // TODO add your handling code here:
        jPanelRegistrarse.setBackground(new Color(148, 13, 30));
    }//GEN-LAST:event_jLabelRegistrarsebuttomMouseEntered

    private void jLabelRegistrarsebuttomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrarsebuttomMouseExited
        // TODO add your handling code here:
        jPanelRegistrarse.setBackground(new Color(180, 45, 49));
    }//GEN-LAST:event_jLabelRegistrarsebuttomMouseExited

    private void jTextFieldCEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCEMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEMousePressed

    private void jPasswordFieldClaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldClaveMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldClaveMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        // TODO add your handling code here:
        jPanelCerrar.setBackground( new Color(232,17,35));
        jLabelCerrar.setForeground( new Color(255,255,255));
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        // TODO add your handling code here:
        jPanelCerrar.setBackground( new Color(255,255,255));
        jLabelCerrar.setForeground( new Color(0,0,0));
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        // TODO add your handling code here:       
        UtilJavaflix.cerrarPrograma();
        
    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void jPasswordFieldClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldClaveActionPerformed

    private void jPasswordFieldClaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldClaveFocusGained
        // TODO add your handling code here:
        if (String.valueOf(jPasswordFieldClave.getPassword()).equals("**********")) {
            jPasswordFieldClave.setText("");
            jPasswordFieldClave.setForeground(Color.black);
        }
        if (jTextFieldCE.getText().isEmpty()) {
            jTextFieldCE.setText("Escriba su correo electrónico");
            jTextFieldCE.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPasswordFieldClaveFocusGained

    private void jTextFieldCEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCEFocusGained
        // TODO add your handling code here:
        if (jTextFieldCE.getText().equals("Escriba su correo electrónico")) {
            jTextFieldCE.setText("");
            jTextFieldCE.setForeground(Color.black);
        }
        if (String.valueOf(jPasswordFieldClave.getPassword()).isEmpty()) {
            jPasswordFieldClave.setText("**********");
            jPasswordFieldClave.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextFieldCEFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and djLabelINICIARSESIONthe form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaPrincipal acceso = new ventanaPrincipal();
                acceso.setLocationRelativeTo(null);
                acceso.setVisible(true);
                
              
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelAccederbuttom;
    private javax.swing.JLabel jLabelCE;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelClave;
    private javax.swing.JLabel jLabelDoblez;
    private javax.swing.JLabel jLabelFondoAcceso;
    private javax.swing.JLabel jLabelFondoEtiquetas;
    private javax.swing.JLabel jLabelINICIARSESION;
    private javax.swing.JLabel jLabelJAVAFLIX;
    private javax.swing.JLabel jLabelJAVAFLIXSombra;
    private javax.swing.JLabel jLabelNotienescuenta;
    private javax.swing.JLabel jLabelRegistrarsebuttom;
    private javax.swing.JPanel jPanelAcceder;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelIntroDatos;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelRegistrarse;
    private javax.swing.JPanel jPanelventana;
    private javax.swing.JPasswordField jPasswordFieldClave;
    private javax.swing.JSeparator jSeparatorCE;
    private javax.swing.JSeparator jSeparatorClave;
    private javax.swing.JTextField jTextFieldCE;
    private javax.swing.JTextField jTextFieldDebug;
    // End of variables declaration//GEN-END:variables
}
